import json
from pathlib import Path

import pytest

from triage_agent.cli import main

SAMPLE_LOG = Path(__file__).resolve().parent.parent / "sample_logs" / "auth_sample.log"


def test_cli_scan_text_output(capsys):
    exit_code = main(["scan", str(SAMPLE_LOG)])
    captured = capsys.readouterr()

    assert exit_code == 0
    assert "Triage Report" in captured.out
    assert "generated by: rule-based" in captured.out


def test_cli_scan_json_output_is_parseable(capsys):
    exit_code = main(["scan", str(SAMPLE_LOG), "--format", "json"])
    captured = capsys.readouterr()

    assert exit_code == 0
    data = json.loads(captured.out)
    assert data["generated_by"] == "rule-based"
    assert data["stats"]["total_findings"] > 0


def test_cli_scan_writes_to_output_file(tmp_path):
    out_file = tmp_path / "report.json"
    exit_code = main(["scan", str(SAMPLE_LOG), "--format", "json", "-o", str(out_file)])

    assert exit_code == 0
    data = json.loads(out_file.read_text())
    assert "findings" in data


def test_cli_scan_missing_file_returns_nonzero(capsys):
    exit_code = main(["scan", "/does/not/exist.log"])
    captured = capsys.readouterr()

    assert exit_code != 0
    assert "error" in captured.err


def test_cli_scan_bad_rules_file_returns_nonzero(tmp_path, capsys):
    bad_rules = tmp_path / "bad.yaml"
    bad_rules.write_text("not_rules: true")

    exit_code = main(["scan", str(SAMPLE_LOG), "--rules", str(bad_rules)])
    captured = capsys.readouterr()

    assert exit_code != 0
    assert "error" in captured.err


def test_cli_requires_a_command(capsys):
    with pytest.raises(SystemExit):
        main([])
