#!/usr/bin/env python3
"""Generate examples/vulnerable_repo/, a synthetic repo for the README demo.

The generated tree is intentionally NOT committed to this repository (see
.gitignore) — it's created here, at run time, rather than checked in as
static files. That's a deliberate choice: static-analysis secret scanners
(including GitHub's own push protection, which every push to this repo
goes through) match on *format*, not on whether a value is actually a
live, reachable credential. A committed file containing a format-plausible
fake AWS/Stripe/Slack key would be blocked the same way a real leaked one
would be. Generating the demo locally sidesteps that without disabling any
scanning — the values below are also built from separate string fragments
rather than one contiguous literal, so this script's own source doesn't
look like a leaked secret either.

Run it, then scan the result:

    python examples/generate_demo.py
    python -m secretscanner.cli examples/vulnerable_repo
"""

from __future__ import annotations

from pathlib import Path


def _join(*parts: str) -> str:
    return "".join(parts)


AWS_ACCESS_KEY_ID = _join("AKIA", "IOSFODNN7", "EXAMPLE")  # AWS's own documented placeholder
AWS_SECRET_ACCESS_KEY = _join("bYLVNGaW8uUCpF9e", "mjxys1fi2xnl", "Q3Fppat3ojd2")
GOOGLE_API_KEY = _join("AIza", "SyD-9tSrke72PouQMnMX-a7eZSW0jkFMBWY")
STRIPE_LIVE_SECRET_KEY = _join("sk_live_", "51H8syntheticNotARealStripeKeyValue00")
SESSION_JWT = _join(
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.",
    "eyJzdWIiOiIxMjM0NTY3ODkwIn0.",
    "dozjgNryP4J3jVmNHl0w5N_XgL0n3I9PlFUP0THsR8U",
)
GENERIC_CLIENT_SECRET = _join("rRue4uEpWbwhK4Bp", "ardjNEF5JLFy")
GENERIC_DB_PASSWORD = _join("3ifbblJ7YE28", "XRqE7qLbmKKD")

GITHUB_TOKEN = _join("ghp_", "9K2mQaW7vXsPzR1nB4tYcL8dJhF3g", "U6oEi0k")
NPM_TOKEN = _join("npm_", "5F8sD2mQaW7vXsPzR1nB4tYcL8d", "JhF3gU6oE")
SLACK_BOT_TOKEN = _join("xoxb-", "909090909090", "-", "808080808080", "-", "aQ2mXsPzR1nB4tYcL8dJhF3g")
SLACK_WEBHOOK_URL = _join(
    "https://hooks.slack.com/services/",
    "T0SYNTHDEMO/B0SYNTHDEMO/",
    "synthDemoWebhookPathValue12345",
)
TWILIO_API_KEY = _join("SK", "15c2e14c5d18bed9235c00400c86b41c")
DB_CONNECTION_STRING = _join(
    "postgres://app_user:", "9fK2pQmX7vB4nR1sT6w", "@db.internal.example.com:5432/prod"
)

PRIVATE_KEY_HEADER = _join("-----BEGIN ", "RSA PRIVATE KEY", "-----")
PRIVATE_KEY_FOOTER = _join("-----END ", "RSA PRIVATE KEY", "-----")
PRIVATE_KEY_BODY = (
    "VGhpcyBpcyBhIHN5bnRoZXRpYyBkZW1vIGZpbGUgZm9yIHNlY3JldC1zY2FubmVyLg==\n"
    "Tm90IGEgcmVhbCBSU0Ega2V5IC0tIGp1c3QgZW5vdWdoIHN0cnVjdHVyZSB0byB0cmlw\n"
    "dGhlIHByaXZhdGUta2V5LWJsb2NrIHNpZ25hdHVyZSBydWxlIGZvciBkZW1vIHB1cnBv\n"
    "c2VzLg==\n"
)

SETTINGS_PY = f'''\
# Synthetic demo config for secret-scanner's README walkthrough.
#
# Every value below is either a randomly generated string with no real-world
# meaning, or a widely-documented placeholder (the AWS access key ID is the
# literal example value from AWS's own docs: docs.aws.amazon.com). Nothing
# here is a live credential. This file is generated by generate_demo.py and
# is not committed to the repository.

AWS_ACCESS_KEY_ID = "{AWS_ACCESS_KEY_ID}"
AWS_SECRET_ACCESS_KEY = "{AWS_SECRET_ACCESS_KEY}"

GOOGLE_MAPS_API_KEY = "{GOOGLE_API_KEY}"

STRIPE_SECRET_KEY = "{STRIPE_LIVE_SECRET_KEY}"

SESSION_TOKEN = "{SESSION_JWT}"

# Generic key/secret assignments with no vendor-specific format -- caught by
# entropy scoring rather than a fixed regex signature.
client_secret = "{GENERIC_CLIENT_SECRET}"
db_password = "{GENERIC_DB_PASSWORD}"

# Not flagged: an obvious placeholder, filtered out by the entropy rule's
# placeholder heuristic.
service_account_key = "your_api_key_here"
'''

DOTENV = f'''\
# Synthetic demo .env -- see examples/README.md. Generated, not committed.

GITHUB_TOKEN={GITHUB_TOKEN}
NPM_TOKEN={NPM_TOKEN}
SLACK_BOT_TOKEN={SLACK_BOT_TOKEN}
SLACK_WEBHOOK_URL={SLACK_WEBHOOK_URL}
TWILIO_API_KEY={TWILIO_API_KEY}
DATABASE_URL={DB_CONNECTION_STRING}
'''

ID_RSA = f"{PRIVATE_KEY_HEADER}\n{PRIVATE_KEY_BODY}{PRIVATE_KEY_FOOTER}\n"


def main() -> None:
    root = Path(__file__).resolve().parent / "vulnerable_repo"
    (root / "config").mkdir(parents=True, exist_ok=True)
    (root / ".ssh").mkdir(parents=True, exist_ok=True)

    (root / "config" / "settings.py").write_text(SETTINGS_PY)
    (root / ".env").write_text(DOTENV)
    (root / ".ssh" / "id_rsa").write_text(ID_RSA)

    print(f"Generated demo repo at {root}")
    print("Scan it with: python -m secretscanner.cli examples/vulnerable_repo")


if __name__ == "__main__":
    main()
