"""Command-line entrypoint: `triage-agent scan <logfile>`."""

from __future__ import annotations

import argparse
import sys

from .pipeline import report_to_json, run_pipeline
from .rules import RuleEngine, RuleLoadError
from .summarizer import DEFAULT_MODEL, AnthropicSummarizer, RuleBasedSummarizer


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="triage-agent", description="Rule-based log triage with optional LLM summarization.")
    sub = parser.add_subparsers(dest="command", required=True)

    scan = sub.add_parser("scan", help="Scan a log file and produce a triage report.")
    scan.add_argument("logfile", help="Path to the log file to scan.")
    scan.add_argument("--rules", default=None, help="Path to a custom rules YAML file (defaults to the bundled ruleset).")
    scan.add_argument("--llm", action="store_true", help="Use Claude to generate a narrative summary (requires ANTHROPIC_API_KEY).")
    scan.add_argument("--model", default=DEFAULT_MODEL, help=f"Model to use with --llm (default: {DEFAULT_MODEL}).")
    scan.add_argument("--format", choices=["text", "json"], default="text", help="Output format.")
    scan.add_argument("-o", "--output", default=None, help="Write output to this file instead of stdout.")

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.command == "scan":
        return _run_scan(args)

    parser.print_help()
    return 1


def _run_scan(args: argparse.Namespace) -> int:
    try:
        engine = RuleEngine.from_file(args.rules)
    except (RuleLoadError, FileNotFoundError) as exc:
        print(f"error: could not load rules: {exc}", file=sys.stderr)
        return 2

    summarizer = AnthropicSummarizer(model=args.model) if args.llm else RuleBasedSummarizer()

    try:
        report = run_pipeline(args.logfile, engine, summarizer)
    except FileNotFoundError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 3

    output = report_to_json(report) if args.format == "json" else _render_text(report)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(output + "\n")
    else:
        print(output)

    return 0


def _render_text(report) -> str:
    header = f"=== Triage Report (generated by: {report.generated_by}) ==="
    return f"{header}\n{report.summary}"


if __name__ == "__main__":
    sys.exit(main())
